-- MySQL Script generated by MySQL Workbench
-- Fri Oct 12 17:17:50 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyectodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectodb` DEFAULT CHARACTER SET utf8 ;
USE `proyectodb` ;

-- -----------------------------------------------------
-- Table `proyectodb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fechaNacimiento` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`, `username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`Docente` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`Docente` (
  `idDocente` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idDocente`, `Usuario_idUsuario`),
  INDEX `fk_Docente_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Docente_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `proyectodb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Juego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`Juego` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`Juego` (
  `idJuego` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idJuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`Curso` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`Curso` (
  `idCurso` INT NOT NULL AUTO_INCREMENT,
  `sePuedeSaltear` TINYINT NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL,
  `Docente_idDocente` INT NULL,
  `Juego_idJuego` INT NOT NULL,
  PRIMARY KEY (`idCurso`, `Juego_idJuego`),
  INDEX `fk_Curso_Docente1_idx` (`Docente_idDocente` ASC),
  INDEX `fk_Curso_Juego1_idx` (`Juego_idJuego` ASC),
  UNIQUE INDEX `Docente_idDocente_UNIQUE` (`Docente_idDocente` ASC),
  CONSTRAINT `fk_Curso_Docente1`
    FOREIGN KEY (`Docente_idDocente`)
    REFERENCES `proyectodb`.`Docente` (`idDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_Juego1`
    FOREIGN KEY (`Juego_idJuego`)
    REFERENCES `proyectodb`.`Juego` (`idJuego`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Escenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`Escenario` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`Escenario` (
  `idEscenario` INT NOT NULL AUTO_INCREMENT,
  `bloquesPermitidos` INT NULL DEFAULT NULL,
  `cantBloquesMax` INT NULL DEFAULT NULL,
  `hint` VARCHAR(45) NULL DEFAULT NULL,
  `posibleSolucion` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idEscenario`, `Curso_idCurso`),
  INDEX `fk_Escenario_Curso1_idx` (`Curso_idCurso` ASC),
  CONSTRAINT `fk_Escenario_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `proyectodb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`Estudiante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`Estudiante` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`Estudiante` (
  `idEstudiante` INT NOT NULL AUTO_INCREMENT,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEstudiante`, `Usuario_idUsuario`),
  INDEX `fk_Estudiante_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Estudiante_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `proyectodb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`CursoIniciado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`CursoIniciado` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`CursoIniciado` (
  `idCursoIniciado` INT NOT NULL AUTO_INCREMENT,
  `Estudiante_idEstudiante` INT NOT NULL,
  `Curso_idCurso` INT NOT NULL,
  PRIMARY KEY (`idCursoIniciado`, `Estudiante_idEstudiante`, `Curso_idCurso`),
  INDEX `fk_CursoIniciado_Estudiante1_idx` (`Estudiante_idEstudiante` ASC),
  INDEX `fk_CursoIniciado_Curso1_idx` (`Curso_idCurso` ASC),
  CONSTRAINT `fk_CursoIniciado_Estudiante1`
    FOREIGN KEY (`Estudiante_idEstudiante`)
    REFERENCES `proyectodb`.`Estudiante` (`idEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CursoIniciado_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `proyectodb`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`EscenarioEnProceso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`EscenarioEnProceso` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`EscenarioEnProceso` (
  `idEscenarioEnProceso` INT NOT NULL AUTO_INCREMENT,
  `puntajeObtenido` INT NULL DEFAULT NULL,
  `solucionBrindada` VARCHAR(45) NULL DEFAULT NULL,
  `fechaInicio` DATE NULL,
  `fechaFinalizacion` DATE NULL,
  `cantidadBloquesUtilizados` INT NULL,
  `tiempoSolucion` FLOAT NULL,
  `intentos` INT NULL,
  `Escenario_idEscenario` INT NOT NULL,
  `CursoIniciado_idCursoIniciado` INT NOT NULL,
  PRIMARY KEY (`idEscenarioEnProceso`, `Escenario_idEscenario`, `CursoIniciado_idCursoIniciado`),
  INDEX `fk_EscenarioEnProceso_Escenario1_idx` (`Escenario_idEscenario` ASC),
  INDEX `fk_EscenarioEnProceso_CursoIniciado1_idx` (`CursoIniciado_idCursoIniciado` ASC),
  CONSTRAINT `fk_EscenarioEnProceso_Escenario1`
    FOREIGN KEY (`Escenario_idEscenario`)
    REFERENCES `proyectodb`.`Escenario` (`idEscenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EscenarioEnProceso_CursoIniciado1`
    FOREIGN KEY (`CursoIniciado_idCursoIniciado`)
    REFERENCES `proyectodb`.`CursoIniciado` (`idCursoIniciado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyectodb`.`EscenarioLaberinto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyectodb`.`EscenarioLaberinto` ;

CREATE TABLE IF NOT EXISTS `proyectodb`.`EscenarioLaberinto` (
  `mapa` VARCHAR(200) NULL,
  `Escenario_idEscenario` INT NOT NULL,
  PRIMARY KEY (`Escenario_idEscenario`),
  CONSTRAINT `fk_EscenarioLaberinto_Escenario1`
    FOREIGN KEY (`Escenario_idEscenario`)
    REFERENCES `proyectodb`.`Escenario` (`idEscenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
